# ETTh1
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 512, "d_model": 512, "dropout": 0.1, "e_layers": 2, "factor": 3, "fc_dropout": 0.1, "horizon": 96, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 192}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 512, "d_model": 512, "dropout": 0.1, "e_layers": 2, "factor": 3, "fc_dropout": 0.1, "horizon": 192, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 336}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 512, "d_model": 512, "dropout": 0.1, "e_layers": 2, "factor": 3, "fc_dropout": 0.1, "horizon": 336, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 512, "d_model": 512, "dropout": 0.1, "e_layers": 2, "factor": 3, "fc_dropout": 0.1, "horizon": 720, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/DUET"

# ETTh2
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 96}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 512, "d_model": 512, "dropout": 0.2, "e_layers": 2, "factor": 3, "fc_dropout": 0.5, "horizon": 96, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 192}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 512, "d_model": 512, "dropout": 0.2, "e_layers": 2, "factor": 3, "fc_dropout": 0.5, "horizon": 192, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 336}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 512, "d_model": 512, "dropout": 0.2, "e_layers": 2, "factor": 3, "fc_dropout": 0.5, "horizon": 336, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 720}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 512, "d_model": 512, "dropout": 0.2, "e_layers": 2, "factor": 3, "fc_dropout": 0.5, "horizon": 720, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/DUET"

# ETTm1
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 512, "d_model": 512, "dropout": 0.1, "e_layers": 2, "factor": 3, "fc_dropout": 0.2, "horizon": 96, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 6, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 192}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 512, "d_model": 512, "dropout": 0.1, "e_layers": 2, "factor": 3, "fc_dropout": 0.2, "horizon": 192, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 6, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 336}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 512, "d_model": 512, "dropout": 0.1, "e_layers": 2, "factor": 3, "fc_dropout": 0.2, "horizon": 336, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 6, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 720}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 512, "d_model": 512, "dropout": 0.1, "e_layers": 2, "factor": 3, "fc_dropout": 0.2, "horizon": 720, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 6, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/DUET"

# ETTm2
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 96}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 512, "d_model": 128, "e_layers": 1, "factor": 3, "hidden_size": 512, "horizon": 96, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 1, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 192}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 512, "d_model": 128, "e_layers": 1, "factor": 3, "hidden_size": 512, "horizon": 192, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 1, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 336}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 512, "d_model": 128, "e_layers": 1, "factor": 3, "hidden_size": 512, "horizon": 336, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 1, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 720}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 512, "d_model": 128, "e_layers": 1, "factor": 3, "hidden_size": 512, "horizon": 720, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 1, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/DUET"

# Weather
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 1024, "d_model": 512, "dropout": 0.1, "e_layers": 2, "factor": 3, "horizon": 96, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 1024, "d_model": 512, "dropout": 0.1, "e_layers": 2, "factor": 3, "horizon": 192, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 1024, "d_model": 512, "dropout": 0.1, "e_layers": 2, "factor": 3, "horizon": 336, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 1024, "d_model": 512, "dropout": 0.1, "e_layers": 2, "factor": 3, "horizon": 720, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/DUET"

# Electricity
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 96}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 1024, "d_model": 512, "dropout": 0.5, "e_layers": 2, "factor": 3, "fc_dropout": 0, "horizon": 96, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 1, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 192}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 1024, "d_model": 512, "dropout": 0.5, "e_layers": 2, "factor": 3, "fc_dropout": 0, "horizon": 192, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 1, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 336}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 1024, "d_model": 512, "dropout": 0.5, "e_layers": 2, "factor": 3, "fc_dropout": 0, "horizon": 336, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 1, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 720}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 1024, "d_model": 512, "dropout": 0.5, "e_layers": 2, "factor": 3, "fc_dropout": 0, "horizon": 720, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 1, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/DUET"

# Solar
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 96}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 1024, "d_model": 512, "dropout": 0.1, "e_layers": 3, "factor": 3, "fc_dropout": 0, "horizon": 96, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 192}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 1024, "d_model": 512, "dropout": 0.1, "e_layers": 3, "factor": 3, "fc_dropout": 0, "horizon": 192, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 336}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 1024, "d_model": 512, "dropout": 0.1, "e_layers": 3, "factor": 3, "fc_dropout": 0, "horizon": 336, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 720}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 1024, "d_model": 512, "dropout": 0.1, "e_layers": 3, "factor": 3, "fc_dropout": 0, "horizon": 720, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 100, "num_experts": 4, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/DUET"

# Traffic
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 96}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 1024, "d_model": 512, "dropout": 0.2, "e_layers": 4, "factor": 3, "fc_dropout": 0, "horizon": 96, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 8, "norm": true, "normalization": true, "num_epochs": 10, "num_experts": 4, "patch_len": 48, "patience": 3, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 192}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 1024, "d_model": 512, "dropout": 0.2, "e_layers": 4, "factor": 3, "fc_dropout": 0, "horizon": 192, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 8, "norm": true, "normalization": true, "num_epochs": 10, "num_experts": 4, "patch_len": 48, "patience": 3, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 336}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 1024, "d_model": 512, "dropout": 0.2, "e_layers": 4, "factor": 3, "fc_dropout": 0, "horizon": 336, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 8, "norm": true, "normalization": true, "num_epochs": 10, "num_experts": 4, "patch_len": 48, "patience": 3, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 720}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 1024, "d_model": 512, "dropout": 0.2, "e_layers": 4, "factor": 3, "fc_dropout": 0, "horizon": 720, "k": 2, "loss": "MAE", "lr": 0.0005, "lradj": "type3", "n_heads": 8, "norm": true, "normalization": true, "num_epochs": 10, "num_experts": 4, "patch_len": 48, "patience": 3, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/DUET"

# Exchange
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 2048, "d_model": 2048, "dropout": 0.2, "e_layers": 1, "factor": 3, "fc_dropout": 0, "hidden_size": 128, "horizon": 96, "k": 3, "loss": "MAE", "lr": 5e-05, "lradj": "type3", "n_heads": 1, "norm": true, "num_epochs": 100, "num_experts": 5, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 192}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 2048, "d_model": 2048, "dropout": 0.2, "e_layers": 1, "factor": 3, "fc_dropout": 0, "hidden_size": 128, "horizon": 192, "k": 3, "loss": "MAE", "lr": 5e-05, "lradj": "type3", "n_heads": 1, "norm": true, "num_epochs": 100, "num_experts": 5, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 336}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 2048, "d_model": 2048, "dropout": 0.2, "e_layers": 1, "factor": 3, "fc_dropout": 0, "hidden_size": 128, "horizon": 336, "k": 3, "loss": "MAE", "lr": 5e-05, "lradj": "type3", "n_heads": 1, "norm": true, "num_epochs": 100, "num_experts": 5, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/DUET"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 720}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 32, "d_ff": 2048, "d_model": 2048, "dropout": 0.2, "e_layers": 1, "factor": 3, "fc_dropout": 0, "hidden_size": 128, "horizon": 720, "k": 3, "loss": "MAE", "lr": 5e-05, "lradj": "type3", "n_heads": 1, "norm": true, "num_epochs": 100, "num_experts": 5, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/DUET"



